export const analyticsEventTypes = [
  "view_home",
  "view_catalog",
  "view_product",
  "search",
  "favorite",
  "add_to_cart",
  "remove_from_cart",
  "start_checkout",
  "select_shipping",
  "purchase",
  "belapop_assistant_opened",
  "belapop_assistant_flow_started",
  "belapop_assistant_flow_completed",
  "belapop_recommendation_viewed",
  "belapop_recommendation_added_to_cart",
  "belapop_kit_added_to_cart",
  "belapop_universe_clicked",
  "belapop_universe_product_clicked",
  "belapop_repurchase_clicked",
  "belapop_post_scan_recommendation_clicked",
  "scan_iniciado",
  "scan_concluido",
  "scan_erro",
  "pdp_vista",
  "reserva_criada",
  "checkout_aberto",
  "pedido_confirmado",
  "pedido_confirmado_server",
  "reserva_abandonada",
  "popclub_entrada",
  "popclub_promocao",
  "quiz_iniciado",
  "quiz_concluido",
  "email_capturado",
  "copilot_respondido",
  "wishlist_adicionado",
  "scan_concluido_server",
  "seller_signup",
  "seller_product_created",
  "seller_product_published",
  "admin_seller_approved",
  "admin_product_approved"
] as const;

export type AnalyticsEventType = (typeof analyticsEventTypes)[number];
